
version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8111:8111
    env_file:
      - .env
    environment:
     - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  adminer:
      image: adminer
      restart: always
      depends_on:
          - db

volumes:
  postgres_data:
