services:
  web:
    build: .
    ports:
      - 8111:8111
    env_file:
      - .env
    environment:
     - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    # volumes:
    #   - .:/app
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:13
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080

volumes:
  postgres_data1:
