# Generated by Django 5.0.6 on 2024-06-01 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typewriter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typewriter',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='typewriter',
            name='user_firstname',
        ),
        migrations.RemoveField(
            model_name='typewriter',
            name='user_lastname',
        ),
        migrations.AddField(
            model_name='typewriter',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
