# Generated by Django 5.1.4 on 2025-01-02 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("typewriter", "0002_remove_typewriter_user_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="textdata",
            name="typewriter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="texts",
                to="typewriter.typewriter",
            ),
        ),
    ]
