# Generated by Django 5.0.6 on 2024-05-20 23:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Textdata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("hashid", models.CharField(max_length=255)),
                ("line_number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Typewriter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_firstname", models.CharField(max_length=255, null=True)),
                ("user_lastname", models.CharField(max_length=255, null=True)),
                (
                    "erika_name",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                ("user_email", models.CharField(max_length=255, null=True)),
                ("uuid", models.CharField(max_length=255, unique=True)),
                ("email", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.IntegerField(default=0)),
                ("chat_active", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_printed", models.BooleanField(default=False)),
                (
                    "typewriter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="typewriter.typewriter",
                    ),
                ),
            ],
        ),
    ]
